name: Run unit tests

on:
  - pull_request
  - push

jobs:

  test_on_cpu:
    strategy:
      matrix:
        os: [["linux", "ubuntu-18.04"], ["mac", "macos-latest"]]
        python_version: [ "3.7", "3.8", "3.9", "3.10" ]

    runs-on: ${{ matrix.os[1] }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Checkout torchrl
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install PyTorch Nightly
        run: |
          pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
          pip install functorch

      - name: Install project dependencies
        run: |
          pip install tqdm tensorboard "hydra-core>=1.1" hydra-submitit-launcher
          pip install moviepy
          pip install dm_control
          pip install 'gym[atari]' "gym[accept-rom-license]" pygame
          pip install pytest pyyaml pytest-instafail
          pip install tensorboard
          pip install wandb
          pip install mlflow
          pip install scipy

      - name: Install torchrl
        run: |
          python setup.py install

      - name: Install test dependencies
        run: |
          pip install numpy pytest pytest-cov codecov pytest-instafail
          pip install unittest-xml-reporting pillow>=4.1.1 scipy av networkx expecttest pyyaml

      - name: Log version string
        run: |
          # Avoid ambiguity of "import torchrl" by deleting the source files.
          rm -rf torchrl/
          python -c "import torchrl; print(torchrl.__version__)"

      - name: Run tests
        run: |
          pytest test/smoke_test.py -v --durations 20
          pytest test/smoke_test_deps.py -v --durations 20
          pytest --instafail -v --durations 20

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
